# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkosCli < Formula
  desc ""
  homepage "https://github.com/workos/workos-cli"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/workos/workos-cli/releases/download/v0.2.0/workos_cli_Darwin_x86_64.tar.gz"
      sha256 "aef99f9c27f5be2af0e2f92e8e8d2604e726ab90237c529c2eadc25665758eef"

      def install
        bin.install "bin/workos"
      end
    end
    on_arm do
      url "https://github.com/workos/workos-cli/releases/download/v0.2.0/workos_cli_Darwin_arm64.tar.gz"
      sha256 "0f5d11c7e50f3d7b766acdaa49539d03058babe73be30760c615a78cbf2ad4b1"

      def install
        bin.install "bin/workos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.2.0/workos_cli_Linux_x86_64.tar.gz"
        sha256 "001149eba5c0ed6590eaa65b1ebb67ec393f30e6b6dd369e5cb6924012276f24"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.2.0/workos_cli_Linux_armv6.tar.gz"
        sha256 "5f85acac7533e651b6114c958a244d983a582ea3ebb3fd86c9569633e5fd689c"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.2.0/workos_cli_Linux_arm64.tar.gz"
        sha256 "9f933f92f209413330edcf894cbbf4f5d0c83e97a63735dec979867adee27858"

        def install
          bin.install "bin/workos"
        end
      end
    end
  end
end
