# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkosCli < Formula
  desc ""
  homepage "https://github.com/workos/workos-cli"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/workos/workos-cli/releases/download/v0.3.0/workos_cli_Darwin_x86_64.tar.gz"
      sha256 "1e6cf4ded9983f828638222736f3b60a3c2f8cca9b124a7c777cb2d3a0ec945c"

      def install
        bin.install "bin/workos"
      end
    end
    on_arm do
      url "https://github.com/workos/workos-cli/releases/download/v0.3.0/workos_cli_Darwin_arm64.tar.gz"
      sha256 "06e7c24879b92181b41b6f5497f0eafc281a5cef3125f586504398b306373858"

      def install
        bin.install "bin/workos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.3.0/workos_cli_Linux_x86_64.tar.gz"
        sha256 "4ccc26787291e8a6cba2cb620809c0811625c89d53e9e140314109a863e65563"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.3.0/workos_cli_Linux_armv6.tar.gz"
        sha256 "049f33bf3913f391e842d6fa355b4349ce786c45a394d47575202f6b98bd39e5"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.3.0/workos_cli_Linux_arm64.tar.gz"
        sha256 "5ad13120b737261b094ea73826de53a29e06e4b6357627af6a93e4502447561c"

        def install
          bin.install "bin/workos"
        end
      end
    end
  end
end
