# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorkosCli < Formula
  desc ""
  homepage "https://github.com/workos/workos-cli"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/workos/workos-cli/releases/download/v0.1.0/WorkOS CLIDarwin_x86_64.tar.gz"
      sha256 "33fee941c97439e57f08f9ca9d8b58625cc1a4215ff66d3c17f6143a60ad5088"

      def install
        bin.install "bin/workos"
      end
    end
    on_arm do
      url "https://github.com/workos/workos-cli/releases/download/v0.1.0/WorkOS CLIDarwin_arm64.tar.gz"
      sha256 "b721b647956dffcb47ab53d2de79e166657691ea5d437d6fac0f027df7cad19f"

      def install
        bin.install "bin/workos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.1.0/WorkOS CLILinux_x86_64.tar.gz"
        sha256 "5f235a5784a952dfdc47590713b21fd3213932fe14fd3618f4285d53bc136a06"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.1.0/WorkOS CLILinux_armv6.tar.gz"
        sha256 "5ede1dd6345ffc2cf295f1a4bbc3a9ecc0588ca1fff61f80095ea66a1984bed3"

        def install
          bin.install "bin/workos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/workos/workos-cli/releases/download/v0.1.0/WorkOS CLILinux_arm64.tar.gz"
        sha256 "3f0e72854be37b3dda155f54560be814d2acc7372bdd8c9378be4135ee5d74d8"

        def install
          bin.install "bin/workos"
        end
      end
    end
  end
end
