# typed: false
# frozen_string_literal: true

# Generated by workos/cli release automation (scripts/gen-homebrew-formula.ts).
# DO NOT EDIT — changes are overwritten on the next release.
class Workos < Formula
  desc "Install AuthKit integrations and manage WorkOS resources"
  homepage "https://github.com/workos/cli"
  version "0.23.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/workos/cli/releases/download/v0.23.0/workos-darwin-arm64"
      sha256 "bb786abbabe49e9aea472ac57be2638bceae38ef887059d71d348a4ea302aeef"
    end
    on_intel do
      url "https://github.com/workos/cli/releases/download/v0.23.0/workos-darwin-x64"
      sha256 "4b7ada55298d12e83f03691b258840b0d3152c43b37555ef887ead972c2de098"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/workos/cli/releases/download/v0.23.0/workos-linux-arm64"
      sha256 "8d665f65c9582bb74ec253b48337f8b11054fd866ecf71b2c7ac89907dc83a51"
    end
    on_intel do
      url "https://github.com/workos/cli/releases/download/v0.23.0/workos-linux-x64"
      sha256 "399437b6c6685b7c50e619cfd85382cc7724c3ecf43c5ec050a8ed6be2201aee"
    end
  end

  # Exactly one of the four assets above is downloaded, so the glob resolves to
  # that platform's binary; matches Formula/workos-emulate.rb in the same tap.
  def install
    binary = Dir["workos-*"].first
    odie "No workos-* binary in the staging directory" if binary.nil?
    bin.install binary => "workos"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workos --version")
  end
end
