# typed: strict
# frozen_string_literal: true

# Generated by workos/emulate release automation.
# DO NOT EDIT — changes are overwritten on the next stable release.
class WorkosEmulate < Formula
  desc "Local WorkOS API emulator for tests and development"
  homepage "https://github.com/workos/emulate"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/workos/emulate/releases/download/v0.5.0/workos-emulate-darwin-arm64"
      sha256 "cea06cc59bcf7c57389a2d8f4ecf480594952fc08e9baa28265764ed5181c428"
    end
    on_intel do
      url "https://github.com/workos/emulate/releases/download/v0.5.0/workos-emulate-darwin-x64"
      sha256 "6d0608d6407eb3b502b49095b5aaef46285800ec1f5aef7d3c6bd0ec97de3e11"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/workos/emulate/releases/download/v0.5.0/workos-emulate-linux-arm64"
      sha256 "00d32c81aebef08f21a964ae0f9a0e9a93ce593d5b0d82172fa55b013197b3f4"
    end
    on_intel do
      url "https://github.com/workos/emulate/releases/download/v0.5.0/workos-emulate-linux-x64"
      sha256 "a736707cee72e9a4230d25c3dcdde0aa4dddc2bed708195c3877e384b59da18a"
    end
  end

  def install
    binary = Dir["workos-emulate-*"].first
    bin.install binary => "workos-emulate"
  end

  test do
    assert_match "workos-emulate", shell_output("#{bin}/workos-emulate --help")
  end
end
