# typed: strict
# frozen_string_literal: true

# Generated by workos/emulate release automation.
# DO NOT EDIT — changes are overwritten on the next stable release.
class WorkosEmulate < Formula
  desc "Local WorkOS API emulator for tests and development"
  homepage "https://github.com/workos/emulate"
  version "0.7.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/workos/emulate/releases/download/v0.7.1/workos-emulate-darwin-arm64"
      sha256 "6daef2e55ba0a935b4bb4a43d984b26359a75126226d58ca2c10b6866d46dbb0"
    end
    on_intel do
      url "https://github.com/workos/emulate/releases/download/v0.7.1/workos-emulate-darwin-x64"
      sha256 "fa4fa0b44cddb2a1258ead689fb4ed8efff607093e022ee11d9296e1956460b3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/workos/emulate/releases/download/v0.7.1/workos-emulate-linux-arm64"
      sha256 "d1188c482f0d1af8fe72d1015d297bbc0a1ed819cbf06ccf0898bbafebee45cd"
    end
    on_intel do
      url "https://github.com/workos/emulate/releases/download/v0.7.1/workos-emulate-linux-x64"
      sha256 "3a252bf3047716dae5c19bc90c1ce2799fe286d8956a1849131e3247d68a98ce"
    end
  end

  def install
    binary = Dir["workos-emulate-*"].first
    bin.install binary => "workos-emulate"
  end

  test do
    assert_match "workos-emulate", shell_output("#{bin}/workos-emulate --help")
  end
end
