# typed: false
# frozen_string_literal: true

# Generated by workos/cli release automation (scripts/gen-homebrew-formula.ts).
# DO NOT EDIT — changes are overwritten on the next release.
class Workos < Formula
  desc "Install AuthKit integrations and manage WorkOS resources"
  homepage "https://github.com/workos/cli"
  version "0.20.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/workos/cli/releases/download/v0.20.2/workos-darwin-arm64"
      sha256 "d22340ebcc04f2bc7e9e8e6eae6e27ee7773bb48739bb3e649362ee07628883a"
    end
    on_intel do
      url "https://github.com/workos/cli/releases/download/v0.20.2/workos-darwin-x64"
      sha256 "9eae95b6f9420e52ec89085e6cbd9709d0b016b44e5199799288003a9d6b78e1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/workos/cli/releases/download/v0.20.2/workos-linux-arm64"
      sha256 "cb37f1cc9557b0dd352a34227a2579188677f7365e44476629834443573f86f4"
    end
    on_intel do
      url "https://github.com/workos/cli/releases/download/v0.20.2/workos-linux-x64"
      sha256 "3d54a100072b724547c4f43ec5dc7e613d45c671ba97b0258dd7a8e550cd6724"
    end
  end

  # Exactly one of the four assets above is downloaded, so the glob resolves to
  # that platform's binary; matches Formula/workos-emulate.rb in the same tap.
  def install
    binary = Dir["workos-*"].first
    odie "No workos-* binary in the staging directory" if binary.nil?
    bin.install binary => "workos"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/workos --version")
  end
end
