name: CI test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-bot:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_SANDBOX_LINUX: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems

      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before

      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax

      - name: Run brew test-bot --only-formulae
        run: brew test-bot --only-formulae
